/**
 * Download Center renderers (pure — data in, text out).
 *
 * One source becomes many reusable knowledge products. Every rendered artifact
 * carries citations back to the source moment, so downloaded knowledge stays
 * verifiable outside the app. These functions never call KMOS; the caller passes
 * the already-assembled {@link Source} and {@link ConceptView}s.
 */

import type { ConceptView, Source } from './types.js';
import { formatTimecode } from './transcript.js';

/** Plain, timecoded transcript. */
export function renderTranscriptText(source: Source): string {
  const lines = source.segments.map((s) => `[${formatTimecode(s.startSec)}] ${s.text}`);
  return `${source.title}\n${'='.repeat(source.title.length)}\n\n${lines.join('\n')}\n`;
}

/** Transcript as Markdown, organized under detected chapters. */
export function renderTranscriptMarkdown(source: Source): string {
  const out: string[] = [`# ${source.title}`, '', `_${source.segments.length} segments · ${Math.round(source.durationSec / 60)} min · via Knowledge Studio on KMOS_`, ''];
  if (source.chapters.length === 0) {
    for (const s of source.segments) out.push(`\`[${formatTimecode(s.startSec)}]\` ${s.text}`, '');
    return out.join('\n');
  }
  for (const ch of source.chapters) {
    out.push(`## ${formatTimecode(ch.startSec)} — ${ch.title}`, '');
    for (let i = ch.segmentStart; i <= ch.segmentEnd; i++) {
      const s = source.segments[i];
      if (s) out.push(`\`[${formatTimecode(s.startSec)}]\` ${s.text}`, '');
    }
  }
  return out.join('\n');
}

/** Study notes: each concept, its definition, its strongest quote, and trust. */
export function renderStudyNotes(source: Source, concepts: readonly ConceptView[]): string {
  const out: string[] = [`# Study Notes — ${source.title}`, '', `_Generated by Knowledge Studio. Every concept below is grounded in the source transcript._`, ''];
  out.push('## Chapters', '');
  for (const ch of source.chapters) out.push(`- \`${formatTimecode(ch.startSec)}\` ${ch.title}`);
  out.push('', '## Concepts', '');
  for (const c of concepts) {
    out.push(`### ${c.name}`, '', c.definition || '_No definition._', '');
    const q = c.evidence[0];
    if (q) out.push(`> "${q.quote}"`, `> — ${source.title} @ \`${formatTimecode(q.startSec)}\`${q.timedExactly ? '' : ' (estimated)'}`, '');
    out.push(`_Trust: ${c.trust.trusted ? 'trusted' : 'needs review'} — ${c.trust.reasons.join('; ')}_`, '');
  }
  return out.join('\n');
}

/** Machine-readable concept export. */
export function renderConceptsJson(source: Source, concepts: readonly ConceptView[]): string {
  return JSON.stringify({
    source: { id: source.id, title: source.title, reference: source.reference, durationSec: source.durationSec },
    concepts: concepts.map((c) => ({
      id: c.id, name: c.name, definition: c.definition,
      evidence: c.evidence, related: c.related.map((r) => ({ id: r.id, name: r.name, relation: r.relation })),
      trust: c.trust,
    })),
  }, null, 2);
}

/** The full knowledge package: metadata + transcript + chapters + concepts. */
export function renderPackage(source: Source, concepts: readonly ConceptView[]): string {
  return JSON.stringify({
    generator: 'Knowledge Studio on KMOS',
    source: {
      id: source.id, kind: source.kind, title: source.title, reference: source.reference,
      durationSec: source.durationSec, targetLanguage: source.targetLanguage ?? null,
    },
    chapters: source.chapters,
    segments: source.segments,
    translatedTranscript: source.translatedTranscript ?? null,
    concepts: concepts.map((c) => ({
      id: c.id, name: c.name, definition: c.definition, evidence: c.evidence,
      related: c.related, lineage: c.lineage, trust: c.trust, vocabulary: c.vocabulary,
    })),
    lineageAssets: { source: source.sourceAssetId ?? null, transcript: source.transcriptAssetId ?? null },
  }, null, 2);
}
