/**
 * Download Center renderers (pure — data in, text out).
 *
 * One episode becomes many reusable knowledge products, each carrying citations back to
 * the source moment so downloaded knowledge stays verifiable outside the app. These
 * functions never call KMOS; the caller passes the already-assembled {@link Episode} and
 * {@link ConceptView}s.
 *
 * KCSI-02 WP5/WP7: near-identical to Knowledge Studio's `downloads.ts` — a candidate
 * shared publishing capability (second-consumer evidence).
 */

import type { ConceptView, Episode } from './types.js';
import { formatTimecode } from './transcript.js';

export interface PackageFile {
  readonly name: string;
  readonly mediaType: string;
  readonly content: string;
}

/** Plain, timecoded transcript. */
export function renderTranscriptText(ep: Episode): string {
  const lines = ep.segments.map((s) => `[${formatTimecode(s.startSec)}] ${s.text}`);
  return `${ep.title}\n${'='.repeat(ep.title.length)}\n\n${lines.join('\n')}\n`;
}

/** Transcript as Markdown, organized under detected chapters. */
export function renderTranscriptMarkdown(ep: Episode): string {
  const out: string[] = [`# ${ep.title}`, '', `_${ep.segments.length} segments · ${Math.round(ep.durationSec / 60)} min · via Podcast Studio on KMOS_`, ''];
  if (ep.chapters.length === 0) {
    for (const s of ep.segments) out.push(`\`[${formatTimecode(s.startSec)}]\` ${s.text}`, '');
    return out.join('\n');
  }
  for (const ch of ep.chapters) {
    out.push(`## ${formatTimecode(ch.startSec)} — ${ch.title}`, '');
    for (let i = ch.segmentStart; i <= ch.segmentEnd; i++) {
      const s = ep.segments[i];
      if (s) out.push(`\`[${formatTimecode(s.startSec)}]\` ${s.text}`, '');
    }
  }
  return out.join('\n');
}

/** Show notes: summary, chapters, notable moments, and the clip plan. */
export function renderShowNotes(ep: Episode): string {
  const out: string[] = [`# Show Notes — ${ep.title}`, ''];
  if (ep.show) out.push(`_${ep.show}_`, '');
  if (ep.summary) out.push('## Summary', '', ep.summary, '');
  out.push('## Chapters', '');
  for (const ch of ep.chapters) out.push(`- \`${formatTimecode(ch.startSec)}\` ${ch.title}`);
  if ((ep.moments ?? []).length > 0) {
    out.push('', '## Notable moments', '');
    for (const m of ep.moments!) out.push(`- \`${formatTimecode(m.startSec)}\` ${m.label} — _${m.reason}_`);
  }
  if ((ep.clips ?? []).length > 0) {
    out.push('', '## Clips', '');
    for (const c of ep.clips!) out.push(`- \`${formatTimecode(c.startSec)}–${formatTimecode(c.endSec)}\` **${c.title}** (${c.kind})`);
  }
  return `${out.join('\n')}\n`;
}

/** Study notes: each concept, its definition, its strongest quote, and trust. */
export function renderStudyNotes(ep: Episode, concepts: readonly ConceptView[]): string {
  const out: string[] = [`# Study Notes — ${ep.title}`, '', `_Generated by Podcast Studio. Every concept below is grounded in the episode transcript._`, ''];
  out.push('## Concepts', '');
  for (const c of concepts) {
    out.push(`### ${c.name}`, '', c.definition || '_No definition._', '');
    const q = c.evidence[0];
    if (q) out.push(`> "${q.quote}"`, `> — ${ep.title} @ \`${formatTimecode(q.startSec)}\`${q.timedExactly ? '' : ' (estimated)'}`, '');
    out.push(`_Trust: ${c.trust.trusted ? 'trusted' : 'needs review'} — ${c.trust.reasons.join('; ')}_`, '');
  }
  return out.join('\n');
}

/** Machine-readable concept export. */
export function renderConceptsJson(ep: Episode, concepts: readonly ConceptView[]): string {
  return JSON.stringify({
    episode: { id: ep.id, title: ep.title, reference: ep.reference, durationSec: ep.durationSec },
    concepts: concepts.map((c) => ({
      id: c.id, name: c.name, definition: c.definition,
      evidence: c.evidence, related: c.related.map((r) => ({ id: r.id, name: r.name, relation: r.relation })),
      trust: c.trust,
    })),
  }, null, 2);
}

/** A citation package — how to cite this episode's knowledge, verifiably. */
export function renderCitation(ep: Episode): string {
  const cite = `${ep.show ? `${ep.show}. ` : ''}"${ep.title}." ${ep.reference}${ep.reference.endsWith('.') ? '' : '.'} Processed with Podcast Studio on KMOS.`;
  return `# Citation\n\n${cite}\n\n_Every concept is grounded in a timestamped transcript passage; see study-notes.md._\n`;
}

/** The full knowledge package: metadata + transcript + chapters + moments + concepts. */
export function renderPackageJson(ep: Episode, concepts: readonly ConceptView[]): string {
  return JSON.stringify({
    generator: 'Podcast Studio on KMOS',
    episode: {
      id: ep.id, kind: ep.kind, title: ep.title, show: ep.show ?? null, reference: ep.reference,
      durationSec: ep.durationSec, targetLanguage: ep.targetLanguage ?? null,
    },
    summary: ep.summary ?? null,
    chapters: ep.chapters,
    moments: ep.moments ?? [],
    clips: ep.clips ?? [],
    segments: ep.segments,
    translatedTranscript: ep.translatedTranscript ?? null,
    concepts: concepts.map((c) => ({
      id: c.id, name: c.name, definition: c.definition, evidence: c.evidence,
      related: c.related, lineage: c.lineage, trust: c.trust, vocabulary: c.vocabulary,
    })),
    lineageAssets: { source: ep.sourceAssetId ?? null, transcript: ep.transcriptAssetId ?? null, subtitles: ep.subtitleAssetId ?? null },
  }, null, 2);
}

/** Assemble the complete downloadable package as a set of files. */
export function buildPackage(ep: Episode, concepts: readonly ConceptView[]): PackageFile[] {
  const files: PackageFile[] = [
    { name: 'transcript.md', mediaType: 'text/markdown', content: renderTranscriptMarkdown(ep) },
    { name: 'transcript.txt', mediaType: 'text/plain', content: renderTranscriptText(ep) },
    { name: 'show-notes.md', mediaType: 'text/markdown', content: renderShowNotes(ep) },
    { name: 'study-notes.md', mediaType: 'text/markdown', content: renderStudyNotes(ep, concepts) },
    { name: 'concepts.json', mediaType: 'application/json', content: renderConceptsJson(ep, concepts) },
    { name: 'citation.md', mediaType: 'text/markdown', content: renderCitation(ep) },
    { name: 'package.json', mediaType: 'application/json', content: renderPackageJson(ep, concepts) },
  ];
  if (ep.subtitleSrt) files.push({ name: 'subtitles.srt', mediaType: 'application/x-subrip', content: ep.subtitleSrt });
  if (ep.subtitleVtt) files.push({ name: 'subtitles.vtt', mediaType: 'text/vtt', content: ep.subtitleVtt });
  if (ep.summary) files.push({ name: 'summary.md', mediaType: 'text/markdown', content: `# Summary — ${ep.title}\n\n${ep.summary}\n` });
  if (ep.translatedTranscript) files.push({ name: 'transcript.translated.txt', mediaType: 'text/plain', content: ep.translatedTranscript });
  return files;
}
