/** Self-contained reference web UI (no framework, no build). Served at GET /. */
export const REFERENCE_UI_HTML = [
'<!doctype html><html lang="en"><head><meta charset="utf-8"/>',
'<meta name="viewport" content="width=device-width,initial-scale=1"/>',
'<title>KMOS — Reference Console</title>',
'<style>',
'body{font:14px/1.5 system-ui,sans-serif;margin:0;background:#0e1116;color:#e6edf3}',
'header{padding:14px 20px;background:#161b22;border-bottom:1px solid #30363d}',
'h1{font-size:16px;margin:0}h2{font-size:13px;color:#7d8590;margin:0 0 8px;text-transform:uppercase;letter-spacing:.5px}',
'main{display:grid;grid-template-columns:1fr 1fr;gap:14px;padding:16px;max-width:1100px;margin:0 auto}',
'.card{background:#161b22;border:1px solid #30363d;border-radius:8px;padding:14px}',
'button{background:#238636;color:#fff;border:0;border-radius:6px;padding:7px 12px;cursor:pointer;font-size:13px}',
'button:hover{background:#2ea043}input,textarea{width:100%;box-sizing:border-box;background:#0d1117;color:#e6edf3;border:1px solid #30363d;border-radius:6px;padding:7px;margin:4px 0;font-size:13px}',
'pre{background:#0d1117;border:1px solid #30363d;border-radius:6px;padding:10px;overflow:auto;max-height:240px;font-size:12px;white-space:pre-wrap;word-break:break-word}',
'.muted{color:#7d8590}.ok{color:#3fb950}.bad{color:#f85149}label{font-size:12px;color:#7d8590}',
'</style></head><body>',
'<header><h1>KMOS — Knowledge &amp; Media Operating System · Reference Console</h1>',
'<div class="muted" id="health">checking…</div></header>',
'<main>',
'<section class="card"><h2>1 · Organization &amp; actor</h2>',
'<input id="orgName" placeholder="Organization name" value="Institute of Knowledge"/>',
'<button onclick="createOrg()">Create organization</button>',
'<input id="editorName" placeholder="Editor name" value="Aisha (Editor)"/>',
'<button onclick="createEditor()">Create identity</button><pre id="orgOut" class="muted">no org yet</pre></section>',
'<section class="card"><h2>2 · Import lecture (Media)</h2>',
'<input id="lectureTitle" placeholder="Lecture title" value="On Sincerity"/>',
'<button onclick="importLecture()">Import + transcribe</button><pre id="lectureOut" class="muted">—</pre></section>',
'<section class="card"><h2>3 · Transcript → Knowledge (Language)</h2>',
'<textarea id="transcript" rows="3">Sincerity leads to Purification and lasting Sincerity</textarea>',
'<button onclick="processTranscript()">Extract concepts</button><pre id="conceptOut" class="muted">—</pre></section>',
'<section class="card"><h2>4 · Search knowledge</h2>',
'<input id="q" placeholder="query" value="Sincerity"/>',
'<button onclick="search()">Search</button><pre id="searchOut" class="muted">—</pre></section>',
'<section class="card"><h2>5 · Lineage / chain of custody</h2>',
'<button onclick="lineage()">Show transcript lineage</button><pre id="lineageOut" class="muted">import a lecture first</pre></section>',
'<section class="card"><h2>6 · Publish + governance + trust</h2>',
'<button onclick="publish()">Publish (with approval)</button> ',
'<button onclick="trust()">Assess trust</button><pre id="govOut" class="muted">—</pre></section>',
'<section class="card"><h2>7 · Institutional audit</h2>',
'<button onclick="metrics()">Event metrics</button><pre id="auditOut" class="muted">—</pre></section>',
'</main>',
'<script>',
'var S={org:null,editor:null,transcriptAsset:null,concepts:[]};',
'function show(id,o,ok){var e=document.getElementById(id);e.textContent=typeof o==="string"?o:JSON.stringify(o,null,2);e.className=ok===false?"bad":"";}',
'async function api(method,path,body){var r=await fetch(path,{method:method,headers:{"content-type":"application/json"},body:body?JSON.stringify(body):undefined});var j=await r.json();if(!r.ok)throw j;return j;}',
'async function health(){try{var h=await api("GET","/health");document.getElementById("health").innerHTML="platform <span class=ok>healthy</span> · events "+h.events+" · dead-letters "+h.deadLetters;}catch(e){document.getElementById("health").innerHTML="<span class=bad>unreachable</span>";}}',
'async function createOrg(){try{S.org=await api("POST","/organizations",{name:document.getElementById("orgName").value});show("orgOut",{organization:S.org.id});}catch(e){show("orgOut",e,false);}}',
'async function createEditor(){try{if(!S.org)return show("orgOut","create an organization first",false);S.editor=await api("POST","/identities",{kind:"Human",displayName:document.getElementById("editorName").value,organizationId:S.org.id});show("orgOut",{organization:S.org.id,editor:S.editor.id});}catch(e){show("orgOut",e,false);}}',
'async function importLecture(){try{var r=await api("POST","/lectures",{title:document.getElementById("lectureTitle").value,organizationId:S.org&&S.org.id});S.transcriptAsset=r.transcriptAssetId;show("lectureOut",r);}catch(e){show("lectureOut",e,false);}}',
'async function processTranscript(){try{var r=await api("POST","/transcripts",{transcript:document.getElementById("transcript").value,targetLanguage:"ar",organizationId:S.org&&S.org.id});S.concepts=r.conceptIds||[];show("conceptOut",r);}catch(e){show("conceptOut",e,false);}}',
'async function search(){try{var r=await api("GET","/knowledge?q="+encodeURIComponent(document.getElementById("q").value));show("searchOut",r.map(function(h){return{id:h.subjectId,score:h.score};}));}catch(e){show("searchOut",e,false);}}',
'async function lineage(){try{if(!S.transcriptAsset)return show("lineageOut","import a lecture first",false);var r=await api("GET","/assets/"+encodeURIComponent(S.transcriptAsset)+"/lineage");show("lineageOut",r);}catch(e){show("lineageOut",e,false);}}',
'async function publish(){try{var r=await api("POST","/publications",{title:"On Sincerity (article)",knowledgeIds:S.concepts,assetIds:S.transcriptAsset?[S.transcriptAsset]:[],approver:"Aisha (Editor)",organizationId:S.org&&S.org.id});show("govOut",r);}catch(e){show("govOut",e,false);}}',
'async function trust(){try{if(!S.concepts.length)return show("govOut","extract concepts first",false);var r=await api("GET","/governance/trust/"+encodeURIComponent(S.concepts[0]));show("govOut",r);}catch(e){show("govOut",e,false);}}',
'async function metrics(){try{var r=await api("GET","/events/metrics");show("auditOut",r);}catch(e){show("auditOut",e,false);}}',
'health();',
'</script></body></html>',
].join('\n');
